version: '3'

services:

  #-----------------#
  #  Server Python  #
  #-----------------#

  server-python:
    image: python:3.8-alpine
    container_name: server-python
    working_dir: /usr/server/
    ports:
      - 8800:8800
    volumes:
      - $PWD/server-python/:/usr/server/
      - csv-share:/usr/server/csv/
    command: "python3 server.py"
      
  #-----------------#
  #    Logstash     #
  #-----------------#

  logstash:
    image: docker.elastic.co/logstash/logstash:8.2.0
    container_name: logstash
    volumes:
      - $PWD/logstash/pipeline/:/usr/share/logstash/pipeline/
      - csv-share:/usr/app/logstash/csv/
    environment:
      - XPACK_MONITORING_ENABLED=false

  #-----------------#
  #      Kafka      #
  #-----------------#

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    restart: always
    depends_on:
      - zookeeper
      - broker
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: keylogger-stats
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9093
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - zookeeper
      - broker
      - kafka-ui
    command: >
      bash -c "kafka-topics --bootstrap-server broker:9093 --create --if-not-exists --topic logs --replication-factor 1 --partitions 1
      && kafka-topics --bootstrap-server broker:9093 --create --if-not-exists --topic metadata --replication-factor 1 --partitions 1"

  #-----------------#
  #      Spark      #
  #-----------------#

  #-----------------#
  #  Elasticsearch  #
  #-----------------#

  #-----------------#
  #      Kibana     #
  #-----------------#

volumes:
  csv-share: